// DatingApp-SPA/src/app/register/register.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { AuthService } from '../_services/auth.service';
import { AlertifyService } from '../_services/alertify.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  @Input()valueFromHome: any;
  @Output() cancelRegister = new EventEmitter();
  model: any = {};

  constructor(private authService: AuthService, private alertify: AlertifyService) { }

  ngOnInit() {
  }

  register() {
    this.authService.register(this.model).subscribe(() => {
      this.alertify.success('registration successful');
    }, error => {
      this.alertify.error(error);
    });
  }

  cancel() {
    this.cancelRegister.emit(false);
  }

}

<form #registerForm="ngForm" (ngSubmit)="register()">
  <h2 class="text-center text-primary">Sign Up</h2>
  <hr>

  <div class="form-group">
    <input type="text" class="form-control" required name="username" [(ngModel)]="model.username" placeholder="Username">
  </div>

  <div class="form-group">
    <input type="password" class="form-control" required name="password" [(ngModel)]="model.password" placeholder="Password">
  </div>

  <!-- <div class="form-group">
    <select name="" id="" class="form-control">
      <option value="" *ngFor="let value of valueFromHome">{{ value.name }}</option>
    </select>
  </div> -->

  <div class="form-group text-center">
    <button class="btn btn-success" type="submit" style="margin-right: 10px;">Register</button>
    <button class="btn btn-default" type="button" (click)="cancel()">Cancel</button>
  </div>

</form>

// dating-app-vue/src/views/Register.vue
<template>
    <div class="container">
        <div class="row" style="margin-top: 100px;">
            <div class="col-md-6 offset-3">
                <form>
                    <h2 class="text-center text-primary">Sign Up</h2>
                    <hr>

                    <div class="form-group">
                        <input type="text" class="form-control" required name="username" placeholder="Username">
                    </div>

                    <div class="form-group">
                        <input type="password" class="form-control" required name="password" placeholder="Password">
                    </div>

                    <div class="form-group text-center">
                        <button class="btn btn-success" type="submit" style="margin-right: 10px;">Register</button>
                        <button class="btn btn-default" type="button" >Cancel</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</template>
