// DatingApp-SPA/src/app/members/member-card/member-card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { User } from '../../_models/user';

@Component({
  selector: 'app-member-card',
  templateUrl: './member-card.component.html',
  styleUrls: ['./member-card.component.scss']
})
export class MemberCardComponent implements OnInit {
  @Input() user: User;

  constructor() { }

  ngOnInit() {
  }

}

<div class="card mb-4">
  <div class="card-img-wrapper">
    <img class="card-img-top" src="{{user.photoUrl}}" alt="{{user.knownAs}}">
    <ul class="list-inline member-icons animate text-center">
      <li class="list-inline-item"><button class="btn btn-primary"
          [routerLink]="['/members/', user.id]"><i class="fa fa-user" style="font-size: 10px;"></i></button></li>
      <li class="list-inline-item"><button class="btn btn-primary"><i class="fa fa-heart" style="font-size: 10px;"></i></button></li>
      <li class="list-inline-item"><button class="btn btn-primary"><i class="fa fa-envelope" style="font-size: 10px;"></i></button></li>
    </ul>
  </div>
  <div class="card-body p-1">
    <h6 class="card-title text-center mb-1"><i class="fa fa-user"></i>
      {{user.knownAs}}, {{user.age}}
    </h6>
    <p class="card-text text-muted text-center">{{user.city}}</p>
  </div>
</div>

// dating-app-vue/src/components/MemberCard.vue
<template>
    <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="card border-light mb-3 mr-3" style="max-width: 200px; margin-right: 15px;">
            <div class="card-img-wrapper">
                <div style="overflow: hidden;">
                    <img v-bind:src="member.photoUrl" width="100%" alt="altText"/>
                </div>
                <ul class="list-inline member-icons animate text-center">
                    <li class="list-inline-item">
                        <router-link v-bind:to="'/member/' + member.id" class="btn btn-info"><i class="text-center fa fa-user"></i></router-link>
                        <button class="btn btn-info"><i class="text-center fa fa-heart"></i></button>
                        <button class="btn btn-info"><i class="text-center fa fa-envelope"></i></button>
                    </li>
                </ul>
            </div>
            <div class="card-body text-info">
                <h5 class="card-title text-center">{{member.knownAs}}, {{member.age}}</h5>
                <p class="card-text text-center">{{ member.city }}</p>
            </div>
        </div>        
    </div>
</template>
<style>
.card:hover img {
    transform: scale(1.2, 1.2);
    transition-duration: 500ms;
    transition-timing-function:  ease-out;
}
.card img {
    transform: scale(1.0, 1.0);
    transition-duration: 500ms;
    transition-timing-function:  ease-out;
}
.card-img-wrapper {
    position: relative;
    cursor: pointer;
}
.member-icons {
    position: absolute;
    bottom: -30%;
    left: 0;
    right: 0;
    margin-right: auto;
    margin-left: auto;
    opacity: 0;
}
.btn {
    margin: 5px;
}
.card-img-wrapper:hover .member-icons{
    bottom: 0;
    opacity: 1;
}
.animate {
    transition: all 0.3s ease-in-out;
}
</style>

<script lang="ts">
import Vue from 'vue';
import { Component, Prop } from 'vue-property-decorator';
import { User } from '@/store/models/users';
import { Subscription } from 'rxjs';
import { GetMembers } from '../services/user-api';

@Component({})
export default class MemberCard extends Vue {
    @Prop() private member!: User;
}
</script>
